[project]
name = "billboard-lyrics-theme-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "chatlas>=0.16.0",
    "datetime>=6.0",
    "dotenv>=0.9.9",
    "matplotlib>=3.10.9",
    "numpy>=2.4.4",
    "openai>=2.36.0",
    "pandas>=3.0.2",
    "pyarrow>=24.0.0",
    "pyperclip>=1.11.0",
    "requests>=2.33.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.4.1",
]
